name: CI
on:
  push:
    branches:
      - main
      - "v*"
    tags:
      - "v*"
  pull_request:

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.3

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: staticcheck ./...

  test:
    name: Go Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
      GOBIN: ${{ github.workspace }}/go/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/rotationalio/ensign-benchmarks
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/rotationalio/ensign-benchmarks

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Install Dependencies
        run: |
          go version
          go install github.com/kevinburke/go-bindata/go-bindata@v3.23.0
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
      - name: Code Generation
        run: go generate ./...

      - name: Run Unit Tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic --race ./...

  build:
    name: Go Build
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
      GOBIN: ${{ github.workspace }}/go/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/rotationalio/ensign-benchmarks
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/rotationalio/ensign-benchmarks

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Install Dependencies
        run: |
          go version
          go install github.com/kevinburke/go-bindata/go-bindata@v3.23.0
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0

      - name: Code Generation
        run: go generate ./...

      - name: Build
        run: go build ./cmd/...